### ISSUE TITLE
[LESS] numero id_produit

### ISSUE THREAD

**Issue by cirelevuahc** [GaelBy/Projet_reve#4]
http://192.168.1.73/projet_reve/index.php?page=produit&id_produit=527777
Fatal error: Call to a member function getStatut() on a non-object in /home/was729/sites/projet_reve/apps/produit.php on line 7

**Comment by GaelBy** [comment]
Il semble y avoir un problème général qui peut se retrouver dans plusieurs cas similaires. Il a été pris en compte et va être corrigé. Merci pour ce feedback !

**Comment by GaelBy** [comment]
Une id non existante renvoie vers home
