### ISSUE TITLE
[CRITIC] perte des informations en cas d'erreur / vardump SQL

### ISSUE THREAD

**Issue by cirelevuahc** [GaelBy/Projet_reve#6]
http://192.168.1.73/projet_reve/index.php?page=register

string 'INSERT INTO users (nom,prenom,email,password,date_naissance,telephone,statut,sexe,login) 
                VALUES ('nom','prenom', 'example@example.com','$2y$08$NwIFTL7KYjS5Ag1iaeRsoecBmcoHbbdocDEZQYcPnNqmoKvW7s5gu','1950-01-01 00:00:00','0123456789','1','1','login')' (length=254)

Perte de toutes les informations lorsqu'il y a une erreur.

Nom de rue trop court (<5)

**Comment by GaelBy** [comment]
vardump retiré, les informations sont mémorisées dans le formulaire de register
